# Generated by Django 4.1 on 2024-05-07 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0002_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='final_details',
        ),
    ]
